name: Run All

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: false
        default: staging
        type: choice
        options:
          - staging
          - production

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List workflows in the repo
        id: list_workflows
        run: |
          # Get the list of workflows in the repo using the GitHub API
          curl -s \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" > workflows.json
          cat workflows.json

      - name: Trigger workflows (excluding all.yml)
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          REF: ${{ github.ref }}
          TARGET_ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          # Use jq to filter out the workflows with the specific filenames
          jq -r '.workflows[] | select(.path != "all.yml") | .id' workflows.json | while read workflow_id; do
            echo "Dispatching workflow ID: $workflow_id for environment: ${TARGET_ENVIRONMENT}"
            curl -s -X POST \
              -H "Authorization: token ${REPO_TOKEN}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/${workflow_id}/dispatches" \
              -d "{\"ref\": \"${REF}\", \"inputs\": {\"environment\": \"${TARGET_ENVIRONMENT}\"}}"
          done
